spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1051292147
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
logging:
  level:
    com.fzw.chche.mapper: debug
